### ISSUE TITLE
Not Open dev/midi2

### ISSUE THREAD

**Issue by lyon470** [asb2m10/PiLink#1]

**Comment by lyon470** [comment]
Hello
I have The Problem that Pilink Shows me 
„Could not find dev/Midi2“

Have anyone an Idee ?

**Comment by asb2m10** [comment]
Normal if you boot it up the first time. Usually, you should see another midi device and simply switch to this one. Once updated, you should see the config.py file with the correct midi port.

**Comment by lyon470** [comment]
Do you speak German ?

I can‘t switch to my Midi Device because it is not in the list.
Do you have any Idea ?

**Comment by asb2m10** [comment]
Nein, nur Französisch.

Your MIDI device is not recognized on the PI. If you do `ls -l /dev/midi*` what do it returns ? 
Plug your midi device, then execute `dmesg` to see any kernel message based on the device detection.

**Comment by lyon470** [comment]
When i run  ls -l /dev/midi*  it returns:

ls: cannot access '/dev/midi*': No such file or directory

When i run dmesg it returns:

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.34-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3                                                                                                                                (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1110 SMP Mon Apr 16 15:18:51 B                                                                                                                               ST 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instructio                                                                                                                               n cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c84e40, node_mem_map ba3a100                                                                                                                               0
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] random: fast init done
[    0.000000] percpu: Embedded 17 pages/cpu @ba34a000 s38720 r8192 d22720 u6963                                                                                                                               2
[    0.000000] pcpu-alloc: s38720 r8192 d22720 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1824 bcm2                                                                                                                               708_fb.fbheight=984 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_si                                                                                                                               ze=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTU                                                                                                                               UID=9242c2a8-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet                                                                                                                                splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940236K/970752K available (7168K kernel code, 575K rwdata                                                                                                                               , 2072K rodata, 1024K init, 706K bss, 22324K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c8fd4c   ( 576 kB)
                      .bss : 0x80c96f4c - 0x80d478b4   ( 707 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 25231 entries in 74 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles:                                                                                                                                0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 43980                                                                                                                               46511078ns
[    0.000019] Switching to timer-based delay loop, resolution 52ns
[    0.000266] Console: colour dummy device 80x30
[    0.000285] console [tty1] enabled
[    0.000309] Calibrating delay loop (skipped), value calculated using timer fr                                                                                                                               equency.. 38.40 BogoMIPS (lpj=192000)
[    0.000324] pid_max: default: 32768 minimum: 301
[    0.000636] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000651] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001586] Disabling memory control group subsystem
[    0.001668] CPU: Testing write buffer coherency: ok
[    0.002059] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002431] Setting up static identity map for 0x100000 - 0x10003c
[    0.002548] Hierarchical SRCU implementation.
[    0.003177] smp: Bringing up secondary CPUs ...
[    0.003857] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.004605] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.005333] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.005437] smp: Brought up 1 node, 4 CPUs
[    0.005447] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.005453] CPU: All CPU(s) started in HYP mode.
[    0.005457] CPU: Virtualization extensions available.
[    0.006311] devtmpfs: initialized
[    0.016955] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3                                                                                                                                rev 4
[    0.017178] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, ma                                                                                                                               x_idle_ns: 19112604462750000 ns
[    0.017196] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.017753] pinctrl core: initialized pinctrl subsystem
[    0.018490] NET: Registered protocol family 16
[    0.021211] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.026005] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint                                                                                                                                registers.
[    0.026012] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.026217] Serial: AMBA PL011 UART driver
[    0.027834] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.028292] uart-pl011 3f201000.serial: could not find pctldev for node /soc/                                                                                                                               gpio@7e200000/uart0_pins, deferring probe
[    0.059350] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dma                                                                                                                               chans=0x1
[    0.060874] SCSI subsystem initialized
[    0.061095] usbcore: registered new interface driver usbfs
[    0.061146] usbcore: registered new interface driver hub
[    0.061231] usbcore: registered new device driver usb
[    0.070088] raspberrypi-firmware soc:firmware: Attached to firmware from 2018                                                                                                                               -04-16 18:16
[    0.071500] clocksource: Switched to clocksource arch_sys_counter
[    0.148874] VFS: Disk quotas dquot_6.6.0
[    0.148959] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.149146] FS-Cache: Loaded
[    0.149339] CacheFiles: Loaded
[    0.158158] NET: Registered protocol family 2
[    0.158880] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.158990] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.159176] TCP: Hash tables configured (established 8192 bind 8192)
[    0.159305] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.159349] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.159577] NET: Registered protocol family 1
[    0.160016] RPC: Registered named UNIX socket transport module.
[    0.160021] RPC: Registered udp transport module.
[    0.160026] RPC: Registered tcp transport module.
[    0.160032] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.161629] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counter                                                                                                                               s available
[    0.164368] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.172287] FS-Cache: Netfs 'nfs' registered for caching
[    0.172873] NFS: Registering the id_resolver key type
[    0.172903] Key type id_resolver registered
[    0.172908] Key type id_legacy registered
[    0.172924] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.174776] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 2                                                                                                                               51)
[    0.174897] io scheduler noop registered
[    0.174904] io scheduler deadline registered (default)
[    0.175180] io scheduler cfq registered
[    0.175187] io scheduler mq-deadline registered
[    0.175193] io scheduler kyber registered
[    0.177866] BCM2708FB: allocated DMA memory fad10000
[    0.177893] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.227595] Console: switching to colour frame buffer device 228x61
[    0.257650] bcm2835-rng 3f104000.rng: hwrng registered
[    0.257778] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000                                                                                                                               000(1024 MiB)
[    0.258260] vc-sm: Videocore shared memory driver
[    0.258528] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f2                                                                                                                               00000
[    0.268188] brd: module loaded
[    0.276948] loop: module loaded
[    0.276960] Loading iSCSI transport class v2.0-870.
[    0.277619] libphy: Fixed MDIO Bus: probed
[    0.277714] usbcore: registered new interface driver lan78xx
[    0.277769] usbcore: registered new interface driver smsc95xx
[    0.277786] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.505913] Core Release: 2.80a
[    0.505924] Setting default values for core params
[    0.505955] Finished setting default values for core params
[    0.706214] Using Buffer DMA mode
[    0.706221] Periodic Transfer Interrupt Enhancement - disabled
[    0.706226] Multiprocessor Interrupt Enhancement - disabled
[    0.706233] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.706245] Dedicated Tx FIFOs mode
[    0.706599] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbad                                                                                                                               04000 dma = 0xfad04000 len=9024
[    0.706625] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.706633] dwc_otg: Microframe scheduler enabled
[    0.706688] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x805e6a40
[    0.706699] WARN::hcd_init_fiq:460: FIQ ASM at 0x805e6da8 length 36
[    0.706712] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb87e000
[    0.706769] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.706805] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number                                                                                                                                1
[    0.706838] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.706885] Init: Port Power? op_state=1
[    0.706890] Init: Power Port (0)
[    0.707096] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.707107] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                                                                                               1
[    0.707116] usb usb1: Product: DWC OTG Controller
[    0.707124] usb usb1: Manufacturer: Linux 4.14.34-v7+ dwc_otg_hcd
[    0.707132] usb usb1: SerialNumber: 3f980000.usb
[    0.707747] hub 1-0:1.0: USB hub found
[    0.707787] hub 1-0:1.0: 1 port detected
[    0.708330] dwc_otg: FIQ enabled
[    0.708336] dwc_otg: NAK holdoff enabled
[    0.708342] dwc_otg: FIQ split-transaction FSM enabled
[    0.708351] Module dwc_common_port init
[    0.708590] usbcore: registered new interface driver usb-storage
[    0.708755] mousedev: PS/2 mouse device common for all mice
[    0.708829] IR NEC protocol handler initialized
[    0.708835] IR RC5(x/sz) protocol handler initialized
[    0.708841] IR RC6 protocol handler initialized
[    0.708846] IR JVC protocol handler initialized
[    0.708852] IR Sony protocol handler initialized
[    0.708857] IR SANYO protocol handler initialized
[    0.708862] IR Sharp protocol handler initialized
[    0.708867] IR MCE Keyboard/mouse protocol handler initialized
[    0.708872] IR XMP protocol handler initialized
[    0.709544] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.709810] bcm2835-cpufreq: min=600000 max=1200000
[    0.710166] sdhci: Secure Digital Host Controller Interface driver
[    0.710171] sdhci: Copyright(c) Pierre Ossman
[    0.710528] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.710848] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.710940] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.712348] ledtrig-cpu: registered to indicate activity on CPUs
[    0.712524] hidraw: raw HID events driver (C) Jiri Kosina
[    0.712651] usbcore: registered new interface driver usbhid
[    0.712656] usbhid: USB HID core driver
[    0.713353] vchiq: vchiq_init_state: slot_zero = bad80000, is_master = 0
[    0.714671] [vc_sm_connected_init]: start
[    0.724107] [vc_sm_connected_init]: end - returning 0
[    0.724686] Initializing XFRM netlink socket
[    0.724710] NET: Registered protocol family 17
[    0.724810] Key type dns_resolver registered
[    0.725348] Registering SWP/SWPB emulation handler
[    0.725934] registered taskstats version 1
[    0.731818] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.731892] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud                                                                                                                                = 0) is a PL011 rev2
[    0.733626] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.733634] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.792128] sdhost: log_buf @ bad07000 (fad07000)
[    0.830950] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.832514] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.834061] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.836837] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.871520] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.872576] of_cfs_init
[    0.872718] of_cfs_init: OK
[    0.873237] Waiting for root device PARTUUID=9242c2a8-02...
[    0.921603] Indeed it is in host mode hprt0 = 00021501
[    0.988995] mmc0: host does not support reading read-only switch, assuming wr                                                                                                                               ite-enable
[    0.991735] mmc0: new high speed SDHC card at address 0007
[    0.992286] mmcblk0: mmc0:0007 SD16G 14.4 GiB
[    0.993859]  mmcblk0: p1 p2
[    1.015743] mmc1: new high speed SDIO card at address 0001
[    1.037108] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. O                                                                                                                               pts: (null)
[    1.037164] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.047531] devtmpfs: mounted
[    1.050673] Freeing unused kernel memory: 1024K
[    1.131619] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.131792] Indeed it is in host mode hprt0 = 00001101
[    1.371836] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.371852] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.372560] hub 1-1:1.0: USB hub found
[    1.372646] hub 1-1:1.0: 5 ports detected
[    1.465341] systemd[1]: System time before build time, advancing clock.
[    1.602198] NET: Registered protocol family 10
[    1.603437] Segment Routing with IPv6
[    1.613886] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.638237] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SEL                                                                                                                               INUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +                                                                                                                               XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.638813] systemd[1]: Detected architecture arm.
[    1.639981] systemd[1]: Set hostname to <raspberrypi>.
[    1.691815] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.821895] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.821910] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber                                                                                                                               =0
[    1.824683] smsc95xx v1.0.6
[    1.914894] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-                                                                                                                               1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:aa:26:45
[    2.011570] usb 1-1.2: new low-speed USB device number 4 using dwc_otg
[    2.132623] systemd[1]: Listening on Syslog Socket.
[    2.133181] systemd[1]: Listening on udev Control Socket.
[    2.150268] systemd[1]: Listening on udev Kernel Socket.
[    2.151098] systemd[1]: Created slice User and Session Slice.
[    2.151375] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.151542] systemd[1]: Reached target Swap.
[    2.152367] systemd[1]: Set up automount Arbitrary Executable File Formats Fi                                                                                                                               le System Automount Point.
[    2.169607] usb 1-1.2: New USB device found, idVendor=03f0, idProduct=0024
[    2.169626] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                                               =0
[    2.169634] usb 1-1.2: Product: HP Basic USB Keyboard
[    2.169643] usb 1-1.2: Manufacturer: CHICONY
[    2.187502] input: CHICONY HP Basic USB Keyboard as /devices/platform/soc/3f9                                                                                                                               80000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:03F0:0024.0001/input/input0
[    2.252566] hid-generic 0003:03F0:0024.0001: input,hidraw0: USB HID v1.10 Key                                                                                                                               board [CHICONY HP Basic USB Keyboard] on usb-3f980000.usb-1.2/input0
[    2.280273] i2c /dev entries driver
[    2.351622] usb 1-1.3: new low-speed USB device number 5 using dwc_otg
[    2.486685] usb 1-1.3: New USB device found, idVendor=17ef, idProduct=6019
[    2.486704] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                                               =0
[    2.486713] usb 1-1.3: Product: Lenovo USB Optical Mouse
[    2.486722] usb 1-1.3: Manufacturer: PixArt
[    2.490924] input: PixArt Lenovo USB Optical Mouse as /devices/platform/soc/3                                                                                                                               f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:17EF:6019.0002/input/input1
[    2.491316] hid-generic 0003:17EF:6019.0002: input,hidraw1: USB HID v1.11 Mou                                                                                                                               se [PixArt Lenovo USB Optical Mouse] on usb-3f980000.usb-1.3/input0
[    2.591636] usb 1-1.4: new full-speed USB device number 6 using dwc_otg
[    2.649222] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    2.726324] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=752d
[    2.726344] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber                                                                                                                               =0
[    2.726353] usb 1-1.4: Product: USB2.0-MIDI
[    2.746379] systemd-journald[88]: Received request to flush runtime journal f                                                                                                                               rom PID 1
[    3.092439] usbcore: registered new interface driver snd-usb-audio
[    3.531316] snd_bcm2835: module is from the staging directory, the quality is                                                                                                                                unknown, you have been warned.
[    3.535555] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[    3.768444] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    3.777127] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdi                                                                                                                               o.bin for chip 0x00a9a6(43430) rev 0x000001
[    3.777418] usbcore: registered new interface driver brcmfmac
[    4.013974] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2                                                                                                                               017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    4.014798] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.                                                                                                                               11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data:                                                                                                                                9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:1                                                                                                                               4
[    6.401232] uart-pl011 3f201000.serial: no DMA platform data
[    6.457314] random: crng init done
[    6.958157] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    6.958178] brcmfmac: power management disabled
[    7.107249] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:1                                                                                                                               02396k SSFS
[    7.443978] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    9.055388] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x41E                                                                                                                               1
[   11.384736] Bluetooth: Core ver 2.22
[   11.384817] NET: Registered protocol family 31
[   11.384823] Bluetooth: HCI device and connection manager initialized
[   11.384848] Bluetooth: HCI socket layer initialized
[   11.384862] Bluetooth: L2CAP socket layer initialized
[   11.384896] Bluetooth: SCO socket layer initialized
[   11.403714] Bluetooth: HCI UART driver ver 2.3
[   11.403742] Bluetooth: HCI UART protocol H4 registered
[   11.403758] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   11.404066] Bluetooth: HCI UART protocol Broadcom registered
[   11.666115] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   11.666127] Bluetooth: BNEP filters: protocol multicast
[   11.666143] Bluetooth: BNEP socket layer initialized
[   11.744817] Bluetooth: RFCOMM TTY layer initialized
[   11.744847] Bluetooth: RFCOMM socket layer initialized
[   11.744870] Bluetooth: RFCOMM ver 1.11
[   14.887793] fuse init (API version 7.26)


I have installed RASPBIAN STRETCH. Maybe this is the Problem ?

**Comment by lyon470** [comment]
![17e38516-5e57-4e30-b66a-3a5e54c53072 1](https://user-images.githubusercontent.com/40247428/41531054-715db900-72f2-11e8-9bb5-b084bfc11f58.jpeg)

This is the message it's showing.

**Comment by lyon470** [comment]
Yes!
Now it has successful connected to my midi device.
But now it shows me another error:

ERROR: substring not found

What do i wrong ?

**Comment by asb2m10** [comment]
Are you using Reaktor or TouchOSC ? I did a fix, please try again with the latest version.

**Comment by lyon470** [comment]
I'am using Touch OSC.

**Comment by lyon470** [comment]
Now it work fine and it shows me the osc message.
But it don't send any midi out.

The message it shows:

==> osc [[ '/Midi/push1', 1.0 ]]

Are something wrong with Touch OSC ?

**Comment by asb2m10** [comment]
You need to configure your layout to send midi messages through OSC

https://hexler.net/docs/touchosc-editor-controls-properties

**Comment by lyon470** [comment]
that have i done.
I have configure a normal midi note : channel 1, note C-2 (0), velocity 0-127.

And i have selected enabled: Touch

**Comment by lyon470** [comment]
Can you help me please?
I don't know what is wrong ?

**Comment by asb2m10** [comment]
Are you able to make it work with your computer and the [https://hexler.net/docs/touchosc-configuration-connections-bridge](bridge) connection ?

In the pilink logs, what message is actually sent from TouchOSC ?

**Comment by lyon470** [comment]
Yes with the Touch OSC Bridge it works perfectly.
So i think the midi signals coming from the layout are good.

![img_5486 1](https://user-images.githubusercontent.com/40247428/42077534-882c5706-7b79-11e8-8f5c-87eb5e7d4c93.JPG)
This was the test with the Touch OSC Bridge.

![img_5485](https://user-images.githubusercontent.com/40247428/42077562-a177883e-7b79-11e8-96f2-2105b4625b44.JPG)
And this is what pilink log messages show.

Is there anything wrong??

**Comment by asb2m10** [comment]
Can you attach the TouchOSC project so I can test this on my side....

PiLink is not configured to /Midi/* messages; this should be real midi messages

**Comment by lyon470** [comment]
I can not attach the Layout file ,because Github don't support that file type.
Maybe it's easier that you put a Layout example in the Pilink folder.
I'm sure that the problem is the Layout configuration from Touch Osc so an working example from you are very good.

**Comment by asb2m10** [comment]
Sorry for the late reply. 

Just send me an email to asb2m10 at gmail.com with the layout as an attachment. I'll check what is the issue.

**Comment by lyon470** [comment]
I have send you an email.
Please check if the email has arrived.
Thanks

**Comment by asb2m10** [comment]
Okay, I know what is the issue; it's been like 3 years since I've played with TouchOSC, my memory was a little blurry for this.

Your configuration doesn't sends any midi messages over OSC ; TouchOSC can send midi message, but only with the proprietary format on a different port; that is not OSC. 

PiLink is actually an emulation of the MissingLink hardware and uses the same protocol over UDP.

To send midi, OSC message name must contain the midi message. Please see this to format what you need to send :  http://www.xmlizer.net/hansLindauer/midiapp.html

Then use the output so PiLink will know what to generate in midi for the OSC message. Please see the example that I've attached to the source.
