### ISSUE TITLE
Another /dev/midi2 problem

### ISSUE THREAD

**Issue by Dranodrinker** [asb2m10/PiLink#2]
After reading thru the issues and solutions the last guy had, I am still having issues. Every time i try to run pilink i get a "no such directory /dev/midi2". I am running on a fresh install of raspbian (which i have rebooted several times with my midi interface installed, still no luck). A little more info; I am attempting to convert TouchOSC to hardware Midi so that I can control my Motu Ultralite interface via the touchOSC template they have created for their hardware.

When I run ls -l /dev/midi* i get no such directory.

dmesg returns:

pi@raspberrypi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c85280, node_mem_map ba39f000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 17 pages/cpu @ba348000 s38720 r8192 d22720 u69632
[    0.000000] pcpu-alloc: s38720 r8192 d22720 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1280 bcm2708_fb.fbheight=1024 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=f62c4625-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940232K/970752K available (7168K kernel code, 576K rwdata, 2076K rodata, 1024K init, 698K bss, 22328K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c9017c   ( 577 kB)
                      .bss : 0x80c97f04 - 0x80d468b0   ( 699 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 25287 entries in 75 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000018] Switching to timer-based delay loop, resolution 52ns
[    0.000266] Console: colour dummy device 80x30
[    0.000284] console [tty1] enabled
[    0.000308] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000323] pid_max: default: 32768 minimum: 301
[    0.000643] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000657] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001593] Disabling memory control group subsystem
[    0.001671] CPU: Testing write buffer coherency: ok
[    0.002085] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002487] Setting up static identity map for 0x100000 - 0x10003c
[    0.002609] Hierarchical SRCU implementation.
[    0.003284] smp: Bringing up secondary CPUs ...
[    0.004062] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.004901] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.005721] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.005826] smp: Brought up 1 node, 4 CPUs
[    0.005837] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.005842] CPU: All CPU(s) started in HYP mode.
[    0.005846] CPU: Virtualization extensions available.
[    0.006771] devtmpfs: initialized
[    0.017002] random: get_random_u32 called from bucket_table_alloc+0xfc/0x24c with crng_init=0
[    0.017767] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.017989] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.018007] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.018559] pinctrl core: initialized pinctrl subsystem
[    0.019304] NET: Registered protocol family 16
[    0.022056] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.026933] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.026941] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.027148] Serial: AMBA PL011 UART driver
[    0.028807] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.029268] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.061055] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.062480] SCSI subsystem initialized
[    0.062698] usbcore: registered new interface driver usbfs
[    0.062750] usbcore: registered new interface driver hub
[    0.062839] usbcore: registered new device driver usb
[    0.070086] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-11-04 16:31
[    0.071506] clocksource: Switched to clocksource arch_sys_counter
[    0.148489] VFS: Disk quotas dquot_6.6.0
[    0.148571] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.148758] FS-Cache: Loaded
[    0.148940] CacheFiles: Loaded
[    0.156880] NET: Registered protocol family 2
[    0.157602] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.157712] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.157897] TCP: Hash tables configured (established 8192 bind 8192)
[    0.158025] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.158070] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.158297] NET: Registered protocol family 1
[    0.158762] RPC: Registered named UNIX socket transport module.
[    0.158768] RPC: Registered udp transport module.
[    0.158774] RPC: Registered tcp transport module.
[    0.158779] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.160425] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.163174] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.171105] FS-Cache: Netfs 'nfs' registered for caching
[    0.171739] NFS: Registering the id_resolver key type
[    0.171769] Key type id_resolver registered
[    0.171774] Key type id_legacy registered
[    0.171789] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.173707] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.173836] io scheduler noop registered
[    0.173842] io scheduler deadline registered (default)
[    0.174009] io scheduler cfq registered
[    0.174016] io scheduler mq-deadline registered
[    0.174022] io scheduler kyber registered
[    0.176730] BCM2708FB: allocated DMA memory fad10000
[    0.176756] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.213670] Console: switching to colour frame buffer device 160x64
[    0.236425] bcm2835-rng 3f104000.rng: hwrng registered
[    0.236558] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.237023] vc-sm: Videocore shared memory driver
[    0.237297] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.246844] brd: module loaded
[    0.255654] loop: module loaded
[    0.255668] Loading iSCSI transport class v2.0-870.
[    0.256354] libphy: Fixed MDIO Bus: probed
[    0.256456] usbcore: registered new interface driver lan78xx
[    0.256509] usbcore: registered new interface driver smsc95xx
[    0.256525] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.284419] dwc_otg 3f980000.usb: base=0xf0980000
[    0.484637] Core Release: 2.80a
[    0.484646] Setting default values for core params
[    0.484678] Finished setting default values for core params
[    0.684937] Using Buffer DMA mode
[    0.684944] Periodic Transfer Interrupt Enhancement - disabled
[    0.684949] Multiprocessor Interrupt Enhancement - disabled
[    0.684956] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.684967] Dedicated Tx FIFOs mode
[    0.685301] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbad04000 dma = 0xfad04000 len=9024
[    0.685327] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.685334] dwc_otg: Microframe scheduler enabled
[    0.685388] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x805ea470
[    0.685399] WARN::hcd_init_fiq:460: FIQ ASM at 0x805ea7d8 length 36
[    0.685412] WARN::hcd_init_fiq:486: MPHI regs_base at 0xf0006000
[    0.685464] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.685498] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.685530] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.685579] Init: Port Power? op_state=1
[    0.685584] Init: Power Port (0)
[    0.685781] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.685792] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.685801] usb usb1: Product: DWC OTG Controller
[    0.685809] usb usb1: Manufacturer: Linux 4.14.79-v7+ dwc_otg_hcd
[    0.685817] usb usb1: SerialNumber: 3f980000.usb
[    0.686427] hub 1-0:1.0: USB hub found
[    0.686465] hub 1-0:1.0: 1 port detected
[    0.687001] dwc_otg: FIQ enabled
[    0.687006] dwc_otg: NAK holdoff enabled
[    0.687011] dwc_otg: FIQ split-transaction FSM enabled
[    0.687023] Module dwc_common_port init
[    0.687279] usbcore: registered new interface driver usb-storage
[    0.687455] mousedev: PS/2 mouse device common for all mice
[    0.687527] IR NEC protocol handler initialized
[    0.687533] IR RC5(x/sz) protocol handler initialized
[    0.687537] IR RC6 protocol handler initialized
[    0.687542] IR JVC protocol handler initialized
[    0.687547] IR Sony protocol handler initialized
[    0.687553] IR SANYO protocol handler initialized
[    0.687558] IR Sharp protocol handler initialized
[    0.687563] IR MCE Keyboard/mouse protocol handler initialized
[    0.687568] IR XMP protocol handler initialized
[    0.688244] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.688502] bcm2835-cpufreq: min=600000 max=1200000
[    0.688855] sdhci: Secure Digital Host Controller Interface driver
[    0.688860] sdhci: Copyright(c) Pierre Ossman
[    0.689202] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.689527] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.689620] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.691044] ledtrig-cpu: registered to indicate activity on CPUs
[    0.691232] hidraw: raw HID events driver (C) Jiri Kosina
[    0.691347] usbcore: registered new interface driver usbhid
[    0.691352] usbhid: USB HID core driver
[    0.692141] vchiq: vchiq_init_state: slot_zero = bad80000, is_master = 0
[    0.693626] [vc_sm_connected_init]: start
[    0.702969] [vc_sm_connected_init]: end - returning 0
[    0.703591] Initializing XFRM netlink socket
[    0.703615] NET: Registered protocol family 17
[    0.703713] Key type dns_resolver registered
[    0.704245] Registering SWP/SWPB emulation handler
[    0.704830] registered taskstats version 1
[    0.710613] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.710690] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.712486] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.712496] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.772152] sdhost: log_buf @ bad07000 (fad07000)
[    0.807825] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.809395] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.810963] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.813751] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.851538] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.852564] of_cfs_init
[    0.852657] of_cfs_init: OK
[    0.853229] Waiting for root device PARTUUID=f62c4625-02...
[    0.891107] random: fast init done
[    0.901622] Indeed it is in host mode hprt0 = 00021501
[    0.990429] mmc1: new high speed SDIO card at address 0001
[    0.998651] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.001258] mmc0: new high speed SDHC card at address 1388
[    1.001733] mmcblk0: mmc0:1388 USD00 14.7 GiB
[    1.003125]  mmcblk0: p1 p2
[    1.032945] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.032995] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.033692] devtmpfs: mounted
[    1.037201] Freeing unused kernel memory: 1024K
[    1.111554] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.111677] Indeed it is in host mode hprt0 = 00001101
[    1.361851] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.361865] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.362559] hub 1-1:1.0: USB hub found
[    1.362637] hub 1-1:1.0: 5 ports detected
[    1.535105] systemd[1]: System time before build time, advancing clock.
[    1.653980] NET: Registered protocol family 10
[    1.655038] Segment Routing with IPv6
[    1.664651] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.681588] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.682167] random: systemd: uninitialized urandom read (16 bytes read)
[    1.687837] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.688407] systemd[1]: Detected architecture arm.
[    1.689216] systemd[1]: Set hostname to <raspberrypi>.
[    1.729619] random: systemd: uninitialized urandom read (16 bytes read)
[    1.749359] random: systemd-gpt-aut: uninitialized urandom read (16 bytes read)
[    1.811935] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.811951] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.814729] smsc95xx v1.0.6
[    1.904996] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:c5:c2:21
[    2.001574] usb 1-1.2: new low-speed USB device number 4 using dwc_otg
[    2.119870] systemd[1]: Listening on udev Kernel Socket.
[    2.120956] systemd[1]: Created slice User and Session Slice.
[    2.121254] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.121476] systemd[1]: Listening on fsck to fsckd communication Socket.
[    2.122379] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.143366] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.143782] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    2.154482] usb 1-1.2: New USB device found, idVendor=413c, idProduct=2003
[    2.154499] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.154508] usb 1-1.2: Product: Dell USB Keyboard
[    2.154518] usb 1-1.2: Manufacturer: Dell
[    2.173811] input: Dell Dell USB Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:413C:2003.0001/input/input0
[    2.210800] i2c /dev entries driver
[    2.242846] hid-generic 0003:413C:2003.0001: input,hidraw0: USB HID v1.10 Keyboard [Dell Dell USB Keyboard] on usb-3f980000.usb-1.2/input0
[    2.541627] usb 1-1.3: new full-speed USB device number 5 using dwc_otg
[    2.676238] usb 1-1.3: New USB device found, idVendor=041e, idProduct=3f0e
[    2.676254] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.676263] usb 1-1.3: Product: E-MU XMidi1X1 Tab
[    2.676271] usb 1-1.3: Manufacturer: E-MU Systems,Inc.
[    2.676281] usb 1-1.3: SerialNumber: E-MU-E6-3F0E-07D90A1E-1014A-TAB
[    2.718784] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    2.776346] usb 1-1.4: new full-speed USB device number 6 using dwc_otg
[    2.819340] systemd-journald[93]: Received request to flush runtime journal from PID 1
[    2.902257] usbcore: registered new interface driver snd-usb-audio
[    2.905477] usb 1-1.4: New USB device found, idVendor=1b1c, idProduct=1b2f
[    2.905496] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.905506] usb 1-1.4: Product: Corsair Gaming SABRE RGB Mouse
[    2.905517] usb 1-1.4: Manufacturer: Corsair
[    2.905526] usb 1-1.4: SerialNumber: 07036031AEB8046955A19679F5001945
[    2.911435] input: Corsair Corsair Gaming SABRE RGB Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:1B1C:1B2F.0002/input/input1
[    2.912023] hid-generic 0003:1B1C:1B2F.0002: input,hidraw1: USB HID v1.11 Mouse [Corsair Corsair Gaming SABRE RGB Mouse] on usb-3f980000.usb-1.4/input0
[    2.918600] input: Corsair Corsair Gaming SABRE RGB Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:1B1C:1B2F.0003/input/input2
[    2.982452] hid-generic 0003:1B1C:1B2F.0003: input,hiddev96,hidraw2: USB HID v1.11 Mouse [Corsair Corsair Gaming SABRE RGB Mouse] on usb-3f980000.usb-1.4/input1
[    2.982851] usbhid 1-1.4:1.2: couldn't find an input interrupt endpoint
[    3.788638] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    3.801170] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[    4.023256] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    4.030423] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    4.030711] usbcore: registered new interface driver brcmfmac
[    4.297372] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    4.298327] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14
[    5.133214] random: crng init done
[    5.133231] random: 7 urandom warning(s) missed due to ratelimiting
[    5.155443] uart-pl011 3f201000.serial: no DMA platform data
[    5.622576] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    5.622748] brcmfmac: power management disabled
[    6.145177] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    6.146163] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    6.390742] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[    6.632564] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[    9.625522] Bluetooth: Core ver 2.22
[    9.625726] NET: Registered protocol family 31
[    9.625733] Bluetooth: HCI device and connection manager initialized
[    9.627740] Bluetooth: HCI socket layer initialized
[    9.627771] Bluetooth: L2CAP socket layer initialized
[    9.627830] Bluetooth: SCO socket layer initialized
[    9.652920] Bluetooth: HCI UART driver ver 2.3
[    9.652931] Bluetooth: HCI UART protocol H4 registered
[    9.652935] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    9.653135] Bluetooth: HCI UART protocol Broadcom registered
[    9.995280] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    9.995287] Bluetooth: BNEP filters: protocol multicast
[    9.995303] Bluetooth: BNEP socket layer initialized
[   10.038825] Bluetooth: RFCOMM TTY layer initialized
[   10.038844] Bluetooth: RFCOMM socket layer initialized
[   10.038868] Bluetooth: RFCOMM ver 1.11
[   11.582196] fuse init (API version 7.26)
[ 1452.435117] usb 1-1.4: USB disconnect, device number 6
pi@raspberrypi:~ $

I can see my midi interface when i run aconnect -l

pi@raspberrypi:~ $ aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'E-MU XMidi1X1 Tab' [type=kernel,card=1]
    0 'E-MU XMidi1X1 Tab MIDI 1'
pi@raspberrypi:~ $

Ideas?

**Comment by asb2m10** [comment]
Hi,

Can you send me the output of those commands ? 

`$ lsmod | grep midi`
`$ find /dev -name "*midi*"`

Thanks.

**Comment by Dranodrinker** [comment]
pi@raspberrypi:~ $ lsmod | grep midi
snd_usbmidi_lib        32768  1 snd_usb_audio
snd_rawmidi            32768  1 snd_usbmidi_lib
snd_seq_device         16384  1 snd_rawmidi
snd                    69632  10 snd_hwdep,snd_usb_audio,snd_timer,snd_rawmidi,snd_usbmidi_lib,snd_seq_device,snd_bcm2835,snd_pcm


pi@raspberrypi:~ $ find /dev -name "*midi*"
/dev/snd/midiC1D0

Thanks for your help!

**Comment by asb2m10** [comment]
OSS modules doesn't seems to be loaded for this. 

Change this line in config.py  :
`mididev = '/dev/snd/midiC1D0'`

It's been a while since I have to know the ruling about ALSA naming convention.

**Comment by Dranodrinker** [comment]
That helped. I can run the pilink.sh from terminal without getting that error. Here is the new output, does this seem right?

pi@raspberrypi:~/pilink $ ./pilink.sh
[[[ pilink ]]]
LISTENING UDP PORT 8000

Now when I use the web interface and try to select my midi device nothing is listed. Also I have yet to successfully connect to the PI with TouchOSC.

Also just noticed that my current client ip is 127.0.0.1 which seems strange?

**Comment by asb2m10** [comment]
127.0.0.1 is normal if your browser is running on the Raspberry Pi. 

I've commited a fix to find other midi devices within the /dev directory.

**Comment by Dranodrinker** [comment]
So I got pilink working as far as connecting to it via touchosc and I am logging messages from my tablet, but I still cant get it to actually send anything out my midi device. I have /dev/snd/midiC1D0 selected on the web interface. 

"amidi --port="hw:1,0,0" --dump" returns the expected midi messages when I use the interface's input and an external midi keyboard.

Ideas? Thanks again for all of your help!

**Comment by asb2m10** [comment]
What is the content of the pilink logs while you are generating notes ?
